a=int(input("enter the first number: "))
b=int(input("enter the second number: "))
print(f"Addition: {a+b}")
print(f"Subtraction: {a-b}")
print(f"Multiplication: {a*b}")
print(f"Division: {a*b}")
print(f"floor division: {a//b}")
print(f"Modulas: {a%b}")
print(f"exponetions: {a**b}")